//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por ESTRUCTURA DATOS WINAPI.rc
//
#define IDCANCEL3                       3
#define IDCANCEL2                       4
#define IDREPORTEE                      4
#define MENUCHIQUITO                    101
#define ESPECIALIDADES                  105
#define MEDICOS                         107
#define CITAS                           109
#define CONSULTAS                       111
#define REG_USUARIO                     111
#define PACIENTE                        113
#define IDD_DIALOG1                     119
#define PRINCIPAL                       120
#define CITAS_TODAS                     121
#define CITAS_MEDICO                    122
#define CITAS_ESPECIALIDAD              123
#define CITAS_SEMANA                    124
#define INICIO_SESION                   125
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_EDIT2                       1009
#define IDC_EDIT3                       1010
#define IDC_EDIT4                       1011
#define IDC_COMBO1                      1012
#define IDC_EDIT7                       1012
#define IDC_EDIT1                       1013
#define IDC_COMBO5                      1014
#define IDC_EDIT12                      1014
#define IDC_PACIENTE                    1014
#define IDC_COMBO2                      1015
#define IDC_COMBO3                      1016
#define IDC_EDIT10                      1016
#define IDC_COMBO4                      1017
#define IDC_EDIT8                       1017
#define IDC_RADIO1                      1018
#define IDC_EDIT9                       1018
#define IDC_NUMCITA                     1018
#define IDC_RADIO2                      1019
#define IDC_COMBO6                      1019
#define IDC_RADIO3                      1020
#define IDC_EDIT11                      1020
#define IDC_RADIO4                      1021
#define IDC_EDIT5                       1022
#define IDC_EDAD                        1022
#define IDC_NOMPACIENTE                 1022
#define IDC_EDIT6                       1023
#define IDC_ESPE                        1023
#define IDC_NOMPACIENTE2                1023
#define IDC_DATETIMEPICKER1             1024
#define IDC_FECHA                       1024
#define IDC_MED                         1024
#define IDC_ESPE2                       1024
#define IDC_MED2                        1025
#define IDC_CHECK1                      1026
#define IDC_LUNES                       1026
#define IDC_CHECK2                      1027
#define IDC_MARTES                      1027
#define IDC_MINUTO                      1027
#define IDC_CHECK4                      1029
#define IDC_MIERCOLES                   1029
#define IDC_CHECK5                      1030
#define IDC_JUEVES                      1030
#define IDC_CHECK6                      1031
#define IDC_DATETIMEPICKER2             1031
#define IDC_VIERNES                     1031
#define IDC_GUARDAR                     1032
#define IDC_PATERNO                     1033
#define IDC_MATERNO                     1034
#define IDC_NOMBRE                      1035
#define IDC_USUARIO                     1036
#define IDC_CLAVE                       1038
#define IDMODIFICAR                     1039
#define IDELIMINAR                      1040
#define FOTOMED                         1041
#define IDC_ESPECIALIDAD                1042
#define IDC_TELEFONO                    1043
#define IDC_REFE                        1044
#define IDC_ELIMINAR                    1046
#define IDC_MODIFICAR                   1047
#define IDC_MEDICO                      1047
#define IDC_HORA                        1048
#define IDC_MINUTOS                     1049
#define IDC_FECHITA                     1050
#define IDC_CONSULTORIO                 1051
#define IDGUARDAR                       1052
#define IDC_ESPECIAL                    1053
#define IDC_FOTOMEDICO                  1054
#define IDC_NOMMEDICO                   1055
#define IDC_NCITA                       1056
#define IDC_FECHAS                      1057
#define IDC_CONSULT                     1058
#define IDC_ESTCITA                     1059
#define IDC_DESCR                       1060
#define IDC_COMBOCITAS                  1061
#define IDC_ATENDIDA                    1062
#define IDC_CANCELAR                    1063
#define IDREPORTE                       1064
#define IDC_BUSCAR                      1065
#define IDC_SEMANACITA                  1066
#define IDC_ARCHIVO                     1067
#define IDC_NOMBREMEDICO                1068
#define IDC_NOMBREESPECIA               1069
#define IDC_MES                         1070
#define IDC_CEDULA                      1071
#define IDC_BUSCA                       1072
#define IDBORRAR                        1073
#define ID_USUARIOS_REGISTRAR           40001
#define ID_CONSULTARCITAS_PORMEDICO     40002
#define ID_CONSULTARCITAS_PORSEMANA     40003
#define ID_CONSULTARCITAS_PORESPECIALIDAD 40004
#define ID_MENUPRINCIPAL                40005
#define ID_CONSULTARCITAS_CITASENGENERAL 40006
#define ID_CITAS                        40007
#define ID_PACIENTES                    40008
#define ID_MEDICOS                      40009
#define ID_USUARIOS                     40010
#define ID_ESPECIALIDADES               40011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
